# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from boundflow.v1 import lifecycle_pb2 as boundflow_dot_v1_dot_lifecycle__pb2

GRPC_GENERATED_VERSION = '1.81.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in boundflow/v1/lifecycle_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class WorkflowServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateWorkflow = channel.unary_unary(
                '/boundflow.v1.WorkflowService/CreateWorkflow',
                request_serializer=boundflow_dot_v1_dot_lifecycle__pb2.CreateWorkflowRequest.SerializeToString,
                response_deserializer=boundflow_dot_v1_dot_lifecycle__pb2.CreateWorkflowResponse.FromString,
                _registered_method=True)
        self.InvokeWorkflow = channel.unary_unary(
                '/boundflow.v1.WorkflowService/InvokeWorkflow',
                request_serializer=boundflow_dot_v1_dot_lifecycle__pb2.InvokeWorkflowRequest.SerializeToString,
                response_deserializer=boundflow_dot_v1_dot_lifecycle__pb2.InvokeWorkflowResponse.FromString,
                _registered_method=True)
        self.DeleteWorkflow = channel.unary_unary(
                '/boundflow.v1.WorkflowService/DeleteWorkflow',
                request_serializer=boundflow_dot_v1_dot_lifecycle__pb2.DeleteWorkflowRequest.SerializeToString,
                response_deserializer=boundflow_dot_v1_dot_lifecycle__pb2.DeleteWorkflowResponse.FromString,
                _registered_method=True)
        self.GetWorkflow = channel.unary_unary(
                '/boundflow.v1.WorkflowService/GetWorkflow',
                request_serializer=boundflow_dot_v1_dot_lifecycle__pb2.GetWorkflowRequest.SerializeToString,
                response_deserializer=boundflow_dot_v1_dot_lifecycle__pb2.GetWorkflowResponse.FromString,
                _registered_method=True)
        self.ListWorkflows = channel.unary_unary(
                '/boundflow.v1.WorkflowService/ListWorkflows',
                request_serializer=boundflow_dot_v1_dot_lifecycle__pb2.ListWorkflowsRequest.SerializeToString,
                response_deserializer=boundflow_dot_v1_dot_lifecycle__pb2.ListWorkflowsResponse.FromString,
                _registered_method=True)
        self.SetAgentRuntimePolicy = channel.unary_unary(
                '/boundflow.v1.WorkflowService/SetAgentRuntimePolicy',
                request_serializer=boundflow_dot_v1_dot_lifecycle__pb2.SetAgentRuntimePolicyRequest.SerializeToString,
                response_deserializer=boundflow_dot_v1_dot_lifecycle__pb2.SetAgentRuntimePolicyResponse.FromString,
                _registered_method=True)
        self.SetAgentLifecyclePolicy = channel.unary_unary(
                '/boundflow.v1.WorkflowService/SetAgentLifecyclePolicy',
                request_serializer=boundflow_dot_v1_dot_lifecycle__pb2.SetAgentLifecyclePolicyRequest.SerializeToString,
                response_deserializer=boundflow_dot_v1_dot_lifecycle__pb2.SetAgentLifecyclePolicyResponse.FromString,
                _registered_method=True)
        self.DeleteAgent = channel.unary_unary(
                '/boundflow.v1.WorkflowService/DeleteAgent',
                request_serializer=boundflow_dot_v1_dot_lifecycle__pb2.DeleteAgentRequest.SerializeToString,
                response_deserializer=boundflow_dot_v1_dot_lifecycle__pb2.DeleteAgentResponse.FromString,
                _registered_method=True)
        self.SetWorkflowLifecyclePolicy = channel.unary_unary(
                '/boundflow.v1.WorkflowService/SetWorkflowLifecyclePolicy',
                request_serializer=boundflow_dot_v1_dot_lifecycle__pb2.SetWorkflowLifecyclePolicyRequest.SerializeToString,
                response_deserializer=boundflow_dot_v1_dot_lifecycle__pb2.SetWorkflowLifecyclePolicyResponse.FromString,
                _registered_method=True)
        self.GetWorkflowLifecyclePolicy = channel.unary_unary(
                '/boundflow.v1.WorkflowService/GetWorkflowLifecyclePolicy',
                request_serializer=boundflow_dot_v1_dot_lifecycle__pb2.GetWorkflowLifecyclePolicyRequest.SerializeToString,
                response_deserializer=boundflow_dot_v1_dot_lifecycle__pb2.GetWorkflowLifecyclePolicyResponse.FromString,
                _registered_method=True)
        self.GetAgentRuntimePolicy = channel.unary_unary(
                '/boundflow.v1.WorkflowService/GetAgentRuntimePolicy',
                request_serializer=boundflow_dot_v1_dot_lifecycle__pb2.GetAgentRuntimePolicyRequest.SerializeToString,
                response_deserializer=boundflow_dot_v1_dot_lifecycle__pb2.GetAgentRuntimePolicyResponse.FromString,
                _registered_method=True)
        self.GetAgentLifecyclePolicy = channel.unary_unary(
                '/boundflow.v1.WorkflowService/GetAgentLifecyclePolicy',
                request_serializer=boundflow_dot_v1_dot_lifecycle__pb2.GetAgentLifecyclePolicyRequest.SerializeToString,
                response_deserializer=boundflow_dot_v1_dot_lifecycle__pb2.GetAgentLifecyclePolicyResponse.FromString,
                _registered_method=True)
        self.ApproveWorkflow = channel.unary_unary(
                '/boundflow.v1.WorkflowService/ApproveWorkflow',
                request_serializer=boundflow_dot_v1_dot_lifecycle__pb2.ApproveWorkflowRequest.SerializeToString,
                response_deserializer=boundflow_dot_v1_dot_lifecycle__pb2.ApproveWorkflowResponse.FromString,
                _registered_method=True)
        self.RejectWorkflow = channel.unary_unary(
                '/boundflow.v1.WorkflowService/RejectWorkflow',
                request_serializer=boundflow_dot_v1_dot_lifecycle__pb2.RejectWorkflowRequest.SerializeToString,
                response_deserializer=boundflow_dot_v1_dot_lifecycle__pb2.RejectWorkflowResponse.FromString,
                _registered_method=True)
        self.SubmitInput = channel.unary_unary(
                '/boundflow.v1.WorkflowService/SubmitInput',
                request_serializer=boundflow_dot_v1_dot_lifecycle__pb2.SubmitInputRequest.SerializeToString,
                response_deserializer=boundflow_dot_v1_dot_lifecycle__pb2.SubmitInputResponse.FromString,
                _registered_method=True)
        self.GetApprovalAudit = channel.unary_unary(
                '/boundflow.v1.WorkflowService/GetApprovalAudit',
                request_serializer=boundflow_dot_v1_dot_lifecycle__pb2.GetApprovalAuditRequest.SerializeToString,
                response_deserializer=boundflow_dot_v1_dot_lifecycle__pb2.GetApprovalAuditResponse.FromString,
                _registered_method=True)
        self.GetApprovalAuditById = channel.unary_unary(
                '/boundflow.v1.WorkflowService/GetApprovalAuditById',
                request_serializer=boundflow_dot_v1_dot_lifecycle__pb2.GetApprovalAuditByIdRequest.SerializeToString,
                response_deserializer=boundflow_dot_v1_dot_lifecycle__pb2.GetApprovalAuditByIdResponse.FromString,
                _registered_method=True)
        self.GetInputAudit = channel.unary_unary(
                '/boundflow.v1.WorkflowService/GetInputAudit',
                request_serializer=boundflow_dot_v1_dot_lifecycle__pb2.GetInputAuditRequest.SerializeToString,
                response_deserializer=boundflow_dot_v1_dot_lifecycle__pb2.GetInputAuditResponse.FromString,
                _registered_method=True)
        self.GetWorkflowPolicyAudit = channel.unary_unary(
                '/boundflow.v1.WorkflowService/GetWorkflowPolicyAudit',
                request_serializer=boundflow_dot_v1_dot_lifecycle__pb2.GetWorkflowPolicyAuditRequest.SerializeToString,
                response_deserializer=boundflow_dot_v1_dot_lifecycle__pb2.GetWorkflowPolicyAuditResponse.FromString,
                _registered_method=True)
        self.GetAgentPolicyAudit = channel.unary_unary(
                '/boundflow.v1.WorkflowService/GetAgentPolicyAudit',
                request_serializer=boundflow_dot_v1_dot_lifecycle__pb2.GetAgentPolicyAuditRequest.SerializeToString,
                response_deserializer=boundflow_dot_v1_dot_lifecycle__pb2.GetAgentPolicyAuditResponse.FromString,
                _registered_method=True)
        self.GetAuditLog = channel.unary_unary(
                '/boundflow.v1.WorkflowService/GetAuditLog',
                request_serializer=boundflow_dot_v1_dot_lifecycle__pb2.GetAuditLogRequest.SerializeToString,
                response_deserializer=boundflow_dot_v1_dot_lifecycle__pb2.GetAuditLogResponse.FromString,
                _registered_method=True)
        self.ActivateWorkflow = channel.unary_unary(
                '/boundflow.v1.WorkflowService/ActivateWorkflow',
                request_serializer=boundflow_dot_v1_dot_lifecycle__pb2.ActivateWorkflowRequest.SerializeToString,
                response_deserializer=boundflow_dot_v1_dot_lifecycle__pb2.ActivateWorkflowResponse.FromString,
                _registered_method=True)
        self.ResolveInterruptedWorkflow = channel.unary_unary(
                '/boundflow.v1.WorkflowService/ResolveInterruptedWorkflow',
                request_serializer=boundflow_dot_v1_dot_lifecycle__pb2.ResolveInterruptedWorkflowRequest.SerializeToString,
                response_deserializer=boundflow_dot_v1_dot_lifecycle__pb2.ResolveInterruptedWorkflowResponse.FromString,
                _registered_method=True)
        self.ListWorkflowRuns = channel.unary_unary(
                '/boundflow.v1.WorkflowService/ListWorkflowRuns',
                request_serializer=boundflow_dot_v1_dot_lifecycle__pb2.ListWorkflowRunsRequest.SerializeToString,
                response_deserializer=boundflow_dot_v1_dot_lifecycle__pb2.ListWorkflowRunsResponse.FromString,
                _registered_method=True)
        self.GetRequestInfo = channel.unary_unary(
                '/boundflow.v1.WorkflowService/GetRequestInfo',
                request_serializer=boundflow_dot_v1_dot_lifecycle__pb2.GetRequestInfoRequest.SerializeToString,
                response_deserializer=boundflow_dot_v1_dot_lifecycle__pb2.GetRequestInfoResponse.FromString,
                _registered_method=True)
        self.GetWorkflowMetrics = channel.unary_unary(
                '/boundflow.v1.WorkflowService/GetWorkflowMetrics',
                request_serializer=boundflow_dot_v1_dot_lifecycle__pb2.GetWorkflowMetricsRequest.SerializeToString,
                response_deserializer=boundflow_dot_v1_dot_lifecycle__pb2.GetWorkflowMetricsResponse.FromString,
                _registered_method=True)


class WorkflowServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def CreateWorkflow(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def InvokeWorkflow(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteWorkflow(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetWorkflow(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListWorkflows(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetAgentRuntimePolicy(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetAgentLifecyclePolicy(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteAgent(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetWorkflowLifecyclePolicy(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetWorkflowLifecyclePolicy(self, request, context):
        """Policy getters — read back the armed (currently-configured) policy for a
        workflow / agent. Mirror the setters; complement the *Audit getters, which
        return firings rather than the armed config.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAgentRuntimePolicy(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAgentLifecyclePolicy(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ApproveWorkflow(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RejectWorkflow(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubmitInput(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetApprovalAudit(self, request, context):
        """Per-type audit getters (workflow_id required); GetAuditLog is the unified,
        time-ordered log (workflow_id optional — omitted = whole tenant group).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetApprovalAuditById(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetInputAudit(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetWorkflowPolicyAudit(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAgentPolicyAudit(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAuditLog(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ActivateWorkflow(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ResolveInterruptedWorkflow(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListWorkflowRuns(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetRequestInfo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetWorkflowMetrics(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_WorkflowServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateWorkflow': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateWorkflow,
                    request_deserializer=boundflow_dot_v1_dot_lifecycle__pb2.CreateWorkflowRequest.FromString,
                    response_serializer=boundflow_dot_v1_dot_lifecycle__pb2.CreateWorkflowResponse.SerializeToString,
            ),
            'InvokeWorkflow': grpc.unary_unary_rpc_method_handler(
                    servicer.InvokeWorkflow,
                    request_deserializer=boundflow_dot_v1_dot_lifecycle__pb2.InvokeWorkflowRequest.FromString,
                    response_serializer=boundflow_dot_v1_dot_lifecycle__pb2.InvokeWorkflowResponse.SerializeToString,
            ),
            'DeleteWorkflow': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteWorkflow,
                    request_deserializer=boundflow_dot_v1_dot_lifecycle__pb2.DeleteWorkflowRequest.FromString,
                    response_serializer=boundflow_dot_v1_dot_lifecycle__pb2.DeleteWorkflowResponse.SerializeToString,
            ),
            'GetWorkflow': grpc.unary_unary_rpc_method_handler(
                    servicer.GetWorkflow,
                    request_deserializer=boundflow_dot_v1_dot_lifecycle__pb2.GetWorkflowRequest.FromString,
                    response_serializer=boundflow_dot_v1_dot_lifecycle__pb2.GetWorkflowResponse.SerializeToString,
            ),
            'ListWorkflows': grpc.unary_unary_rpc_method_handler(
                    servicer.ListWorkflows,
                    request_deserializer=boundflow_dot_v1_dot_lifecycle__pb2.ListWorkflowsRequest.FromString,
                    response_serializer=boundflow_dot_v1_dot_lifecycle__pb2.ListWorkflowsResponse.SerializeToString,
            ),
            'SetAgentRuntimePolicy': grpc.unary_unary_rpc_method_handler(
                    servicer.SetAgentRuntimePolicy,
                    request_deserializer=boundflow_dot_v1_dot_lifecycle__pb2.SetAgentRuntimePolicyRequest.FromString,
                    response_serializer=boundflow_dot_v1_dot_lifecycle__pb2.SetAgentRuntimePolicyResponse.SerializeToString,
            ),
            'SetAgentLifecyclePolicy': grpc.unary_unary_rpc_method_handler(
                    servicer.SetAgentLifecyclePolicy,
                    request_deserializer=boundflow_dot_v1_dot_lifecycle__pb2.SetAgentLifecyclePolicyRequest.FromString,
                    response_serializer=boundflow_dot_v1_dot_lifecycle__pb2.SetAgentLifecyclePolicyResponse.SerializeToString,
            ),
            'DeleteAgent': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteAgent,
                    request_deserializer=boundflow_dot_v1_dot_lifecycle__pb2.DeleteAgentRequest.FromString,
                    response_serializer=boundflow_dot_v1_dot_lifecycle__pb2.DeleteAgentResponse.SerializeToString,
            ),
            'SetWorkflowLifecyclePolicy': grpc.unary_unary_rpc_method_handler(
                    servicer.SetWorkflowLifecyclePolicy,
                    request_deserializer=boundflow_dot_v1_dot_lifecycle__pb2.SetWorkflowLifecyclePolicyRequest.FromString,
                    response_serializer=boundflow_dot_v1_dot_lifecycle__pb2.SetWorkflowLifecyclePolicyResponse.SerializeToString,
            ),
            'GetWorkflowLifecyclePolicy': grpc.unary_unary_rpc_method_handler(
                    servicer.GetWorkflowLifecyclePolicy,
                    request_deserializer=boundflow_dot_v1_dot_lifecycle__pb2.GetWorkflowLifecyclePolicyRequest.FromString,
                    response_serializer=boundflow_dot_v1_dot_lifecycle__pb2.GetWorkflowLifecyclePolicyResponse.SerializeToString,
            ),
            'GetAgentRuntimePolicy': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAgentRuntimePolicy,
                    request_deserializer=boundflow_dot_v1_dot_lifecycle__pb2.GetAgentRuntimePolicyRequest.FromString,
                    response_serializer=boundflow_dot_v1_dot_lifecycle__pb2.GetAgentRuntimePolicyResponse.SerializeToString,
            ),
            'GetAgentLifecyclePolicy': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAgentLifecyclePolicy,
                    request_deserializer=boundflow_dot_v1_dot_lifecycle__pb2.GetAgentLifecyclePolicyRequest.FromString,
                    response_serializer=boundflow_dot_v1_dot_lifecycle__pb2.GetAgentLifecyclePolicyResponse.SerializeToString,
            ),
            'ApproveWorkflow': grpc.unary_unary_rpc_method_handler(
                    servicer.ApproveWorkflow,
                    request_deserializer=boundflow_dot_v1_dot_lifecycle__pb2.ApproveWorkflowRequest.FromString,
                    response_serializer=boundflow_dot_v1_dot_lifecycle__pb2.ApproveWorkflowResponse.SerializeToString,
            ),
            'RejectWorkflow': grpc.unary_unary_rpc_method_handler(
                    servicer.RejectWorkflow,
                    request_deserializer=boundflow_dot_v1_dot_lifecycle__pb2.RejectWorkflowRequest.FromString,
                    response_serializer=boundflow_dot_v1_dot_lifecycle__pb2.RejectWorkflowResponse.SerializeToString,
            ),
            'SubmitInput': grpc.unary_unary_rpc_method_handler(
                    servicer.SubmitInput,
                    request_deserializer=boundflow_dot_v1_dot_lifecycle__pb2.SubmitInputRequest.FromString,
                    response_serializer=boundflow_dot_v1_dot_lifecycle__pb2.SubmitInputResponse.SerializeToString,
            ),
            'GetApprovalAudit': grpc.unary_unary_rpc_method_handler(
                    servicer.GetApprovalAudit,
                    request_deserializer=boundflow_dot_v1_dot_lifecycle__pb2.GetApprovalAuditRequest.FromString,
                    response_serializer=boundflow_dot_v1_dot_lifecycle__pb2.GetApprovalAuditResponse.SerializeToString,
            ),
            'GetApprovalAuditById': grpc.unary_unary_rpc_method_handler(
                    servicer.GetApprovalAuditById,
                    request_deserializer=boundflow_dot_v1_dot_lifecycle__pb2.GetApprovalAuditByIdRequest.FromString,
                    response_serializer=boundflow_dot_v1_dot_lifecycle__pb2.GetApprovalAuditByIdResponse.SerializeToString,
            ),
            'GetInputAudit': grpc.unary_unary_rpc_method_handler(
                    servicer.GetInputAudit,
                    request_deserializer=boundflow_dot_v1_dot_lifecycle__pb2.GetInputAuditRequest.FromString,
                    response_serializer=boundflow_dot_v1_dot_lifecycle__pb2.GetInputAuditResponse.SerializeToString,
            ),
            'GetWorkflowPolicyAudit': grpc.unary_unary_rpc_method_handler(
                    servicer.GetWorkflowPolicyAudit,
                    request_deserializer=boundflow_dot_v1_dot_lifecycle__pb2.GetWorkflowPolicyAuditRequest.FromString,
                    response_serializer=boundflow_dot_v1_dot_lifecycle__pb2.GetWorkflowPolicyAuditResponse.SerializeToString,
            ),
            'GetAgentPolicyAudit': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAgentPolicyAudit,
                    request_deserializer=boundflow_dot_v1_dot_lifecycle__pb2.GetAgentPolicyAuditRequest.FromString,
                    response_serializer=boundflow_dot_v1_dot_lifecycle__pb2.GetAgentPolicyAuditResponse.SerializeToString,
            ),
            'GetAuditLog': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAuditLog,
                    request_deserializer=boundflow_dot_v1_dot_lifecycle__pb2.GetAuditLogRequest.FromString,
                    response_serializer=boundflow_dot_v1_dot_lifecycle__pb2.GetAuditLogResponse.SerializeToString,
            ),
            'ActivateWorkflow': grpc.unary_unary_rpc_method_handler(
                    servicer.ActivateWorkflow,
                    request_deserializer=boundflow_dot_v1_dot_lifecycle__pb2.ActivateWorkflowRequest.FromString,
                    response_serializer=boundflow_dot_v1_dot_lifecycle__pb2.ActivateWorkflowResponse.SerializeToString,
            ),
            'ResolveInterruptedWorkflow': grpc.unary_unary_rpc_method_handler(
                    servicer.ResolveInterruptedWorkflow,
                    request_deserializer=boundflow_dot_v1_dot_lifecycle__pb2.ResolveInterruptedWorkflowRequest.FromString,
                    response_serializer=boundflow_dot_v1_dot_lifecycle__pb2.ResolveInterruptedWorkflowResponse.SerializeToString,
            ),
            'ListWorkflowRuns': grpc.unary_unary_rpc_method_handler(
                    servicer.ListWorkflowRuns,
                    request_deserializer=boundflow_dot_v1_dot_lifecycle__pb2.ListWorkflowRunsRequest.FromString,
                    response_serializer=boundflow_dot_v1_dot_lifecycle__pb2.ListWorkflowRunsResponse.SerializeToString,
            ),
            'GetRequestInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRequestInfo,
                    request_deserializer=boundflow_dot_v1_dot_lifecycle__pb2.GetRequestInfoRequest.FromString,
                    response_serializer=boundflow_dot_v1_dot_lifecycle__pb2.GetRequestInfoResponse.SerializeToString,
            ),
            'GetWorkflowMetrics': grpc.unary_unary_rpc_method_handler(
                    servicer.GetWorkflowMetrics,
                    request_deserializer=boundflow_dot_v1_dot_lifecycle__pb2.GetWorkflowMetricsRequest.FromString,
                    response_serializer=boundflow_dot_v1_dot_lifecycle__pb2.GetWorkflowMetricsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'boundflow.v1.WorkflowService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('boundflow.v1.WorkflowService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class WorkflowService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateWorkflow(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/boundflow.v1.WorkflowService/CreateWorkflow',
            boundflow_dot_v1_dot_lifecycle__pb2.CreateWorkflowRequest.SerializeToString,
            boundflow_dot_v1_dot_lifecycle__pb2.CreateWorkflowResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def InvokeWorkflow(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/boundflow.v1.WorkflowService/InvokeWorkflow',
            boundflow_dot_v1_dot_lifecycle__pb2.InvokeWorkflowRequest.SerializeToString,
            boundflow_dot_v1_dot_lifecycle__pb2.InvokeWorkflowResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteWorkflow(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/boundflow.v1.WorkflowService/DeleteWorkflow',
            boundflow_dot_v1_dot_lifecycle__pb2.DeleteWorkflowRequest.SerializeToString,
            boundflow_dot_v1_dot_lifecycle__pb2.DeleteWorkflowResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetWorkflow(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/boundflow.v1.WorkflowService/GetWorkflow',
            boundflow_dot_v1_dot_lifecycle__pb2.GetWorkflowRequest.SerializeToString,
            boundflow_dot_v1_dot_lifecycle__pb2.GetWorkflowResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListWorkflows(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/boundflow.v1.WorkflowService/ListWorkflows',
            boundflow_dot_v1_dot_lifecycle__pb2.ListWorkflowsRequest.SerializeToString,
            boundflow_dot_v1_dot_lifecycle__pb2.ListWorkflowsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetAgentRuntimePolicy(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/boundflow.v1.WorkflowService/SetAgentRuntimePolicy',
            boundflow_dot_v1_dot_lifecycle__pb2.SetAgentRuntimePolicyRequest.SerializeToString,
            boundflow_dot_v1_dot_lifecycle__pb2.SetAgentRuntimePolicyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetAgentLifecyclePolicy(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/boundflow.v1.WorkflowService/SetAgentLifecyclePolicy',
            boundflow_dot_v1_dot_lifecycle__pb2.SetAgentLifecyclePolicyRequest.SerializeToString,
            boundflow_dot_v1_dot_lifecycle__pb2.SetAgentLifecyclePolicyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteAgent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/boundflow.v1.WorkflowService/DeleteAgent',
            boundflow_dot_v1_dot_lifecycle__pb2.DeleteAgentRequest.SerializeToString,
            boundflow_dot_v1_dot_lifecycle__pb2.DeleteAgentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetWorkflowLifecyclePolicy(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/boundflow.v1.WorkflowService/SetWorkflowLifecyclePolicy',
            boundflow_dot_v1_dot_lifecycle__pb2.SetWorkflowLifecyclePolicyRequest.SerializeToString,
            boundflow_dot_v1_dot_lifecycle__pb2.SetWorkflowLifecyclePolicyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetWorkflowLifecyclePolicy(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/boundflow.v1.WorkflowService/GetWorkflowLifecyclePolicy',
            boundflow_dot_v1_dot_lifecycle__pb2.GetWorkflowLifecyclePolicyRequest.SerializeToString,
            boundflow_dot_v1_dot_lifecycle__pb2.GetWorkflowLifecyclePolicyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAgentRuntimePolicy(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/boundflow.v1.WorkflowService/GetAgentRuntimePolicy',
            boundflow_dot_v1_dot_lifecycle__pb2.GetAgentRuntimePolicyRequest.SerializeToString,
            boundflow_dot_v1_dot_lifecycle__pb2.GetAgentRuntimePolicyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAgentLifecyclePolicy(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/boundflow.v1.WorkflowService/GetAgentLifecyclePolicy',
            boundflow_dot_v1_dot_lifecycle__pb2.GetAgentLifecyclePolicyRequest.SerializeToString,
            boundflow_dot_v1_dot_lifecycle__pb2.GetAgentLifecyclePolicyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ApproveWorkflow(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/boundflow.v1.WorkflowService/ApproveWorkflow',
            boundflow_dot_v1_dot_lifecycle__pb2.ApproveWorkflowRequest.SerializeToString,
            boundflow_dot_v1_dot_lifecycle__pb2.ApproveWorkflowResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RejectWorkflow(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/boundflow.v1.WorkflowService/RejectWorkflow',
            boundflow_dot_v1_dot_lifecycle__pb2.RejectWorkflowRequest.SerializeToString,
            boundflow_dot_v1_dot_lifecycle__pb2.RejectWorkflowResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SubmitInput(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/boundflow.v1.WorkflowService/SubmitInput',
            boundflow_dot_v1_dot_lifecycle__pb2.SubmitInputRequest.SerializeToString,
            boundflow_dot_v1_dot_lifecycle__pb2.SubmitInputResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetApprovalAudit(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/boundflow.v1.WorkflowService/GetApprovalAudit',
            boundflow_dot_v1_dot_lifecycle__pb2.GetApprovalAuditRequest.SerializeToString,
            boundflow_dot_v1_dot_lifecycle__pb2.GetApprovalAuditResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetApprovalAuditById(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/boundflow.v1.WorkflowService/GetApprovalAuditById',
            boundflow_dot_v1_dot_lifecycle__pb2.GetApprovalAuditByIdRequest.SerializeToString,
            boundflow_dot_v1_dot_lifecycle__pb2.GetApprovalAuditByIdResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetInputAudit(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/boundflow.v1.WorkflowService/GetInputAudit',
            boundflow_dot_v1_dot_lifecycle__pb2.GetInputAuditRequest.SerializeToString,
            boundflow_dot_v1_dot_lifecycle__pb2.GetInputAuditResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetWorkflowPolicyAudit(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/boundflow.v1.WorkflowService/GetWorkflowPolicyAudit',
            boundflow_dot_v1_dot_lifecycle__pb2.GetWorkflowPolicyAuditRequest.SerializeToString,
            boundflow_dot_v1_dot_lifecycle__pb2.GetWorkflowPolicyAuditResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAgentPolicyAudit(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/boundflow.v1.WorkflowService/GetAgentPolicyAudit',
            boundflow_dot_v1_dot_lifecycle__pb2.GetAgentPolicyAuditRequest.SerializeToString,
            boundflow_dot_v1_dot_lifecycle__pb2.GetAgentPolicyAuditResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAuditLog(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/boundflow.v1.WorkflowService/GetAuditLog',
            boundflow_dot_v1_dot_lifecycle__pb2.GetAuditLogRequest.SerializeToString,
            boundflow_dot_v1_dot_lifecycle__pb2.GetAuditLogResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ActivateWorkflow(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/boundflow.v1.WorkflowService/ActivateWorkflow',
            boundflow_dot_v1_dot_lifecycle__pb2.ActivateWorkflowRequest.SerializeToString,
            boundflow_dot_v1_dot_lifecycle__pb2.ActivateWorkflowResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ResolveInterruptedWorkflow(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/boundflow.v1.WorkflowService/ResolveInterruptedWorkflow',
            boundflow_dot_v1_dot_lifecycle__pb2.ResolveInterruptedWorkflowRequest.SerializeToString,
            boundflow_dot_v1_dot_lifecycle__pb2.ResolveInterruptedWorkflowResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListWorkflowRuns(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/boundflow.v1.WorkflowService/ListWorkflowRuns',
            boundflow_dot_v1_dot_lifecycle__pb2.ListWorkflowRunsRequest.SerializeToString,
            boundflow_dot_v1_dot_lifecycle__pb2.ListWorkflowRunsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetRequestInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/boundflow.v1.WorkflowService/GetRequestInfo',
            boundflow_dot_v1_dot_lifecycle__pb2.GetRequestInfoRequest.SerializeToString,
            boundflow_dot_v1_dot_lifecycle__pb2.GetRequestInfoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetWorkflowMetrics(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/boundflow.v1.WorkflowService/GetWorkflowMetrics',
            boundflow_dot_v1_dot_lifecycle__pb2.GetWorkflowMetricsRequest.SerializeToString,
            boundflow_dot_v1_dot_lifecycle__pb2.GetWorkflowMetricsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
