# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from boundflow.v1 import worker_pb2 as boundflow_dot_v1_dot_worker__pb2

GRPC_GENERATED_VERSION = '1.81.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in boundflow/v1/worker_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class WorkerServiceStub:
    """WorkerService is implemented by the control plane server.
    The worker (customer SDK) connects as a gRPC client and opens a
    bidirectional stream. The server drives the session — sending
    LaunchOperation and PollOperation commands — while the worker
    responds with status updates.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.WorkerSession = channel.stream_stream(
                '/boundflow.v1.WorkerService/WorkerSession',
                request_serializer=boundflow_dot_v1_dot_worker__pb2.WorkerMessage.SerializeToString,
                response_deserializer=boundflow_dot_v1_dot_worker__pb2.ServerCommand.FromString,
                _registered_method=True)


class WorkerServiceServicer:
    """WorkerService is implemented by the control plane server.
    The worker (customer SDK) connects as a gRPC client and opens a
    bidirectional stream. The server drives the session — sending
    LaunchOperation and PollOperation commands — while the worker
    responds with status updates.
    """

    def WorkerSession(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_WorkerServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'WorkerSession': grpc.stream_stream_rpc_method_handler(
                    servicer.WorkerSession,
                    request_deserializer=boundflow_dot_v1_dot_worker__pb2.WorkerMessage.FromString,
                    response_serializer=boundflow_dot_v1_dot_worker__pb2.ServerCommand.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'boundflow.v1.WorkerService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('boundflow.v1.WorkerService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class WorkerService:
    """WorkerService is implemented by the control plane server.
    The worker (customer SDK) connects as a gRPC client and opens a
    bidirectional stream. The server drives the session — sending
    LaunchOperation and PollOperation commands — while the worker
    responds with status updates.
    """

    @staticmethod
    def WorkerSession(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/boundflow.v1.WorkerService/WorkerSession',
            boundflow_dot_v1_dot_worker__pb2.WorkerMessage.SerializeToString,
            boundflow_dot_v1_dot_worker__pb2.ServerCommand.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
