# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: boundflow/v1/workflow.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'boundflow/v1/workflow.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1b\x62oundflow/v1/workflow.proto\x12\x0c\x62oundflow.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"t\n\x0eWorkflowConfig\x12\x0f\n\x07version\x18\x01 \x01(\x05\x12\x1e\n\x16invoke_timeout_seconds\x18\x02 \x01(\x05\x12\x1c\n\x14repeat_every_seconds\x18\x03 \x01(\x05\x12\x13\n\x0btriggerable\x18\x04 \x01(\x08\"\xf5\x01\n\x08Workflow\x12\n\n\x02id\x18\x01 \x01(\t\x12\x15\n\rworkflow_type\x18\x02 \x01(\t\x12\x11\n\ttenant_id\x18\x03 \x01(\t\x12.\n\ncreated_at\x18\x06 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x35\n\x0fworkflow_config\x18\x08 \x01(\x0b\x32\x1c.boundflow.v1.WorkflowConfig\x12\x17\n\x0flifecycle_state\x18\t \x01(\t\x12\x33\n\x0eworkflow_state\x18\n \x01(\x0e\x32\x1b.boundflow.v1.WorkflowState*\x9f\x01\n\rWorkflowState\x12\x1e\n\x1aWORKFLOW_STATE_UNSPECIFIED\x10\x00\x12\x19\n\x15WORKFLOW_STATE_ACTIVE\x10\x01\x12\x19\n\x15WORKFLOW_STATE_PAUSED\x10\x02\x12\x1b\n\x17WORKFLOW_STATE_COOLDOWN\x10\x03\x12\x1b\n\x17WORKFLOW_STATE_DISABLED\x10\x04\x42=Z;github.com/boundflow/boundflow/gen/boundflow/v1;boundflowv1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'boundflow.v1.workflow_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z;github.com/boundflow/boundflow/gen/boundflow/v1;boundflowv1'
  _globals['_WORKFLOWSTATE']._serialized_start=445
  _globals['_WORKFLOWSTATE']._serialized_end=604
  _globals['_WORKFLOWCONFIG']._serialized_start=78
  _globals['_WORKFLOWCONFIG']._serialized_end=194
  _globals['_WORKFLOW']._serialized_start=197
  _globals['_WORKFLOW']._serialized_end=442
# @@protoc_insertion_point(module_scope)
