# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: boundflow/v1/worker.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'boundflow/v1/worker.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from boundflow.v1 import operation_pb2 as boundflow_dot_v1_dot_operation__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19\x62oundflow/v1/worker.proto\x12\x0c\x62oundflow.v1\x1a\x1c\x62oundflow/v1/operation.proto\"\x8c\x01\n\rWorkerMessage\x12\x12\n\nsession_id\x18\x01 \x01(\t\x12+\n\x05ready\x18\x02 \x01(\x0b\x32\x1a.boundflow.v1.ReadyForWorkH\x00\x12/\n\x06update\x18\x03 \x01(\x0b\x32\x1d.boundflow.v1.OperationUpdateH\x00\x42\t\n\x07payload\"C\n\x10WorkerCapability\x12\x15\n\rworkflow_type\x18\x01 \x01(\t\x12\x18\n\x10workflow_version\x18\x02 \x01(\x05\"D\n\x0cReadyForWork\x12\x34\n\x0c\x63\x61pabilities\x18\x01 \x03(\x0b\x32\x1e.boundflow.v1.WorkerCapability\"\\\n\x0fOperationUpdate\x12\x14\n\x0coperation_id\x18\x01 \x01(\t\x12\x33\n\x06result\x18\x02 \x01(\x0b\x32#.boundflow.v1.AtomicOperationResult\"|\n\rServerCommand\x12/\n\x06launch\x18\x01 \x01(\x0b\x32\x1d.boundflow.v1.LaunchOperationH\x00\x12/\n\x06\x63\x61ncel\x18\x02 \x01(\x0b\x32\x1d.boundflow.v1.CancelOperationH\x00\x42\t\n\x07payload\"C\n\x0fLaunchOperation\x12\x30\n\toperation\x18\x01 \x01(\x0b\x32\x1d.boundflow.v1.AtomicOperation\"\'\n\x0f\x43\x61ncelOperation\x12\x14\n\x0coperation_id\x18\x01 \x01(\t2^\n\rWorkerService\x12M\n\rWorkerSession\x12\x1b.boundflow.v1.WorkerMessage\x1a\x1b.boundflow.v1.ServerCommand(\x01\x30\x01\x42=Z;github.com/boundflow/boundflow/gen/boundflow/v1;boundflowv1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'boundflow.v1.worker_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z;github.com/boundflow/boundflow/gen/boundflow/v1;boundflowv1'
  _globals['_WORKERMESSAGE']._serialized_start=74
  _globals['_WORKERMESSAGE']._serialized_end=214
  _globals['_WORKERCAPABILITY']._serialized_start=216
  _globals['_WORKERCAPABILITY']._serialized_end=283
  _globals['_READYFORWORK']._serialized_start=285
  _globals['_READYFORWORK']._serialized_end=353
  _globals['_OPERATIONUPDATE']._serialized_start=355
  _globals['_OPERATIONUPDATE']._serialized_end=447
  _globals['_SERVERCOMMAND']._serialized_start=449
  _globals['_SERVERCOMMAND']._serialized_end=573
  _globals['_LAUNCHOPERATION']._serialized_start=575
  _globals['_LAUNCHOPERATION']._serialized_end=642
  _globals['_CANCELOPERATION']._serialized_start=644
  _globals['_CANCELOPERATION']._serialized_end=683
  _globals['_WORKERSERVICE']._serialized_start=685
  _globals['_WORKERSERVICE']._serialized_end=779
# @@protoc_insertion_point(module_scope)
