// Code generated by MockGen. DO NOT EDIT.
// Source: internal/storage/repository.go
//
// Generated by this command:
//
//	mockgen -source=internal/storage/repository.go -destination=internal/storage/mocks/repository.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	time "time"

	convergeplanev1 "github.com/convergeplane/convergeplane/gen/convergeplane/v1"
	domain "github.com/convergeplane/convergeplane/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockTenantGroupRepository is a mock of TenantGroupRepository interface.
type MockTenantGroupRepository struct {
	ctrl     *gomock.Controller
	recorder *MockTenantGroupRepositoryMockRecorder
	isgomock struct{}
}

// MockTenantGroupRepositoryMockRecorder is the mock recorder for MockTenantGroupRepository.
type MockTenantGroupRepositoryMockRecorder struct {
	mock *MockTenantGroupRepository
}

// NewMockTenantGroupRepository creates a new mock instance.
func NewMockTenantGroupRepository(ctrl *gomock.Controller) *MockTenantGroupRepository {
	mock := &MockTenantGroupRepository{ctrl: ctrl}
	mock.recorder = &MockTenantGroupRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTenantGroupRepository) EXPECT() *MockTenantGroupRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockTenantGroupRepository) Create(ctx context.Context, group *domain.TenantGroup) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, group)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockTenantGroupRepositoryMockRecorder) Create(ctx, group any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockTenantGroupRepository)(nil).Create), ctx, group)
}

// Delete mocks base method.
func (m *MockTenantGroupRepository) Delete(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockTenantGroupRepositoryMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockTenantGroupRepository)(nil).Delete), ctx, id)
}

// Get mocks base method.
func (m *MockTenantGroupRepository) Get(ctx context.Context, id string) (*domain.TenantGroup, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, id)
	ret0, _ := ret[0].(*domain.TenantGroup)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockTenantGroupRepositoryMockRecorder) Get(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockTenantGroupRepository)(nil).Get), ctx, id)
}

// MockTenantRepository is a mock of TenantRepository interface.
type MockTenantRepository struct {
	ctrl     *gomock.Controller
	recorder *MockTenantRepositoryMockRecorder
	isgomock struct{}
}

// MockTenantRepositoryMockRecorder is the mock recorder for MockTenantRepository.
type MockTenantRepositoryMockRecorder struct {
	mock *MockTenantRepository
}

// NewMockTenantRepository creates a new mock instance.
func NewMockTenantRepository(ctrl *gomock.Controller) *MockTenantRepository {
	mock := &MockTenantRepository{ctrl: ctrl}
	mock.recorder = &MockTenantRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTenantRepository) EXPECT() *MockTenantRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockTenantRepository) Create(ctx context.Context, tenant *domain.Tenant) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, tenant)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockTenantRepositoryMockRecorder) Create(ctx, tenant any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockTenantRepository)(nil).Create), ctx, tenant)
}

// Delete mocks base method.
func (m *MockTenantRepository) Delete(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockTenantRepositoryMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockTenantRepository)(nil).Delete), ctx, id)
}

// Get mocks base method.
func (m *MockTenantRepository) Get(ctx context.Context, id string) (*domain.Tenant, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, id)
	ret0, _ := ret[0].(*domain.Tenant)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockTenantRepositoryMockRecorder) Get(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockTenantRepository)(nil).Get), ctx, id)
}

// MockResourceInstanceRepository is a mock of ResourceInstanceRepository interface.
type MockResourceInstanceRepository struct {
	ctrl     *gomock.Controller
	recorder *MockResourceInstanceRepositoryMockRecorder
	isgomock struct{}
}

// MockResourceInstanceRepositoryMockRecorder is the mock recorder for MockResourceInstanceRepository.
type MockResourceInstanceRepositoryMockRecorder struct {
	mock *MockResourceInstanceRepository
}

// NewMockResourceInstanceRepository creates a new mock instance.
func NewMockResourceInstanceRepository(ctrl *gomock.Controller) *MockResourceInstanceRepository {
	mock := &MockResourceInstanceRepository{ctrl: ctrl}
	mock.recorder = &MockResourceInstanceRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockResourceInstanceRepository) EXPECT() *MockResourceInstanceRepositoryMockRecorder {
	return m.recorder
}

// ApplyCompletedJob mocks base method.
func (m *MockResourceInstanceRepository) ApplyCompletedJob(ctx context.Context, id string, lifecycleState domain.LifecycleState, version int64) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ApplyCompletedJob", ctx, id, lifecycleState, version)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ApplyCompletedJob indicates an expected call of ApplyCompletedJob.
func (mr *MockResourceInstanceRepositoryMockRecorder) ApplyCompletedJob(ctx, id, lifecycleState, version any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ApplyCompletedJob", reflect.TypeOf((*MockResourceInstanceRepository)(nil).ApplyCompletedJob), ctx, id, lifecycleState, version)
}

// Create mocks base method.
func (m *MockResourceInstanceRepository) Create(ctx context.Context, instance *domain.ResourceInstance) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, instance)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockResourceInstanceRepositoryMockRecorder) Create(ctx, instance any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockResourceInstanceRepository)(nil).Create), ctx, instance)
}

// Get mocks base method.
func (m *MockResourceInstanceRepository) Get(ctx context.Context, id string) (*domain.ResourceInstance, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, id)
	ret0, _ := ret[0].(*domain.ResourceInstance)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockResourceInstanceRepositoryMockRecorder) Get(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockResourceInstanceRepository)(nil).Get), ctx, id)
}

// IncrementTargetVersion mocks base method.
func (m *MockResourceInstanceRepository) IncrementTargetVersion(ctx context.Context, id string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IncrementTargetVersion", ctx, id)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IncrementTargetVersion indicates an expected call of IncrementTargetVersion.
func (mr *MockResourceInstanceRepositoryMockRecorder) IncrementTargetVersion(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IncrementTargetVersion", reflect.TypeOf((*MockResourceInstanceRepository)(nil).IncrementTargetVersion), ctx, id)
}

// StartInvocationAndIncrementVersion mocks base method.
func (m *MockResourceInstanceRepository) StartInvocationAndIncrementVersion(ctx context.Context, id string, invalidStates ...domain.LifecycleState) (int64, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, id}
	for _, a := range invalidStates {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "StartInvocationAndIncrementVersion", varargs...)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// StartInvocationAndIncrementVersion indicates an expected call of StartInvocationAndIncrementVersion.
func (mr *MockResourceInstanceRepositoryMockRecorder) StartInvocationAndIncrementVersion(ctx, id any, invalidStates ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, id}, invalidStates...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StartInvocationAndIncrementVersion", reflect.TypeOf((*MockResourceInstanceRepository)(nil).StartInvocationAndIncrementVersion), varargs...)
}

// UpdateCurrentVersion mocks base method.
func (m *MockResourceInstanceRepository) UpdateCurrentVersion(ctx context.Context, id string, version int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateCurrentVersion", ctx, id, version)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateCurrentVersion indicates an expected call of UpdateCurrentVersion.
func (mr *MockResourceInstanceRepositoryMockRecorder) UpdateCurrentVersion(ctx, id, version any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateCurrentVersion", reflect.TypeOf((*MockResourceInstanceRepository)(nil).UpdateCurrentVersion), ctx, id, version)
}

// UpdateLastCompletedRequestAt mocks base method.
func (m *MockResourceInstanceRepository) UpdateLastCompletedRequestAt(ctx context.Context, id string, t time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateLastCompletedRequestAt", ctx, id, t)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateLastCompletedRequestAt indicates an expected call of UpdateLastCompletedRequestAt.
func (mr *MockResourceInstanceRepositoryMockRecorder) UpdateLastCompletedRequestAt(ctx, id, t any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateLastCompletedRequestAt", reflect.TypeOf((*MockResourceInstanceRepository)(nil).UpdateLastCompletedRequestAt), ctx, id, t)
}

// UpdateLifecycleState mocks base method.
func (m *MockResourceInstanceRepository) UpdateLifecycleState(ctx context.Context, id string, state domain.LifecycleState) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateLifecycleState", ctx, id, state)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateLifecycleState indicates an expected call of UpdateLifecycleState.
func (mr *MockResourceInstanceRepositoryMockRecorder) UpdateLifecycleState(ctx, id, state any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateLifecycleState", reflect.TypeOf((*MockResourceInstanceRepository)(nil).UpdateLifecycleState), ctx, id, state)
}

// UpdateLifecycleStateAndIncrementVersion mocks base method.
func (m *MockResourceInstanceRepository) UpdateLifecycleStateAndIncrementVersion(ctx context.Context, id string, state domain.LifecycleState, invalidStates ...domain.LifecycleState) (int64, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, id, state}
	for _, a := range invalidStates {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "UpdateLifecycleStateAndIncrementVersion", varargs...)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateLifecycleStateAndIncrementVersion indicates an expected call of UpdateLifecycleStateAndIncrementVersion.
func (mr *MockResourceInstanceRepositoryMockRecorder) UpdateLifecycleStateAndIncrementVersion(ctx, id, state any, invalidStates ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, id, state}, invalidStates...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateLifecycleStateAndIncrementVersion", reflect.TypeOf((*MockResourceInstanceRepository)(nil).UpdateLifecycleStateAndIncrementVersion), varargs...)
}

// UpdateSchedulerPartition mocks base method.
func (m *MockResourceInstanceRepository) UpdateSchedulerPartition(ctx context.Context, id, partitionID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateSchedulerPartition", ctx, id, partitionID)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateSchedulerPartition indicates an expected call of UpdateSchedulerPartition.
func (mr *MockResourceInstanceRepositoryMockRecorder) UpdateSchedulerPartition(ctx, id, partitionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateSchedulerPartition", reflect.TypeOf((*MockResourceInstanceRepository)(nil).UpdateSchedulerPartition), ctx, id, partitionID)
}

// MockSchedulerPartitionRepository is a mock of SchedulerPartitionRepository interface.
type MockSchedulerPartitionRepository struct {
	ctrl     *gomock.Controller
	recorder *MockSchedulerPartitionRepositoryMockRecorder
	isgomock struct{}
}

// MockSchedulerPartitionRepositoryMockRecorder is the mock recorder for MockSchedulerPartitionRepository.
type MockSchedulerPartitionRepositoryMockRecorder struct {
	mock *MockSchedulerPartitionRepository
}

// NewMockSchedulerPartitionRepository creates a new mock instance.
func NewMockSchedulerPartitionRepository(ctrl *gomock.Controller) *MockSchedulerPartitionRepository {
	mock := &MockSchedulerPartitionRepository{ctrl: ctrl}
	mock.recorder = &MockSchedulerPartitionRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSchedulerPartitionRepository) EXPECT() *MockSchedulerPartitionRepositoryMockRecorder {
	return m.recorder
}

// AcquireAvailable mocks base method.
func (m *MockSchedulerPartitionRepository) AcquireAvailable(ctx context.Context, ownerID string, leaseDuration time.Duration) (*domain.SchedulerPartition, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AcquireAvailable", ctx, ownerID, leaseDuration)
	ret0, _ := ret[0].(*domain.SchedulerPartition)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AcquireAvailable indicates an expected call of AcquireAvailable.
func (mr *MockSchedulerPartitionRepositoryMockRecorder) AcquireAvailable(ctx, ownerID, leaseDuration any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AcquireAvailable", reflect.TypeOf((*MockSchedulerPartitionRepository)(nil).AcquireAvailable), ctx, ownerID, leaseDuration)
}

// Release mocks base method.
func (m *MockSchedulerPartitionRepository) Release(ctx context.Context, partitionID, ownerID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Release", ctx, partitionID, ownerID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Release indicates an expected call of Release.
func (mr *MockSchedulerPartitionRepositoryMockRecorder) Release(ctx, partitionID, ownerID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Release", reflect.TypeOf((*MockSchedulerPartitionRepository)(nil).Release), ctx, partitionID, ownerID)
}

// Renew mocks base method.
func (m *MockSchedulerPartitionRepository) Renew(ctx context.Context, partitionID, ownerID string, leaseDuration time.Duration) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Renew", ctx, partitionID, ownerID, leaseDuration)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Renew indicates an expected call of Renew.
func (mr *MockSchedulerPartitionRepositoryMockRecorder) Renew(ctx, partitionID, ownerID, leaseDuration any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Renew", reflect.TypeOf((*MockSchedulerPartitionRepository)(nil).Renew), ctx, partitionID, ownerID, leaseDuration)
}

// MockSchedulerRepository is a mock of SchedulerRepository interface.
type MockSchedulerRepository struct {
	ctrl     *gomock.Controller
	recorder *MockSchedulerRepositoryMockRecorder
	isgomock struct{}
}

// MockSchedulerRepositoryMockRecorder is the mock recorder for MockSchedulerRepository.
type MockSchedulerRepositoryMockRecorder struct {
	mock *MockSchedulerRepository
}

// NewMockSchedulerRepository creates a new mock instance.
func NewMockSchedulerRepository(ctrl *gomock.Controller) *MockSchedulerRepository {
	mock := &MockSchedulerRepository{ctrl: ctrl}
	mock.recorder = &MockSchedulerRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSchedulerRepository) EXPECT() *MockSchedulerRepositoryMockRecorder {
	return m.recorder
}

// DeleteTerminalJob mocks base method.
func (m *MockSchedulerRepository) DeleteTerminalJob(ctx context.Context, resourceInstanceID, requestID string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteTerminalJob", ctx, resourceInstanceID, requestID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteTerminalJob indicates an expected call of DeleteTerminalJob.
func (mr *MockSchedulerRepositoryMockRecorder) DeleteTerminalJob(ctx, resourceInstanceID, requestID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteTerminalJob", reflect.TypeOf((*MockSchedulerRepository)(nil).DeleteTerminalJob), ctx, resourceInstanceID, requestID)
}

// GetCompletedJobRequestIDs mocks base method.
func (m *MockSchedulerRepository) GetCompletedJobRequestIDs(ctx context.Context, partitionID string) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCompletedJobRequestIDs", ctx, partitionID)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCompletedJobRequestIDs indicates an expected call of GetCompletedJobRequestIDs.
func (mr *MockSchedulerRepositoryMockRecorder) GetCompletedJobRequestIDs(ctx, partitionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCompletedJobRequestIDs", reflect.TypeOf((*MockSchedulerRepository)(nil).GetCompletedJobRequestIDs), ctx, partitionID)
}

// GetFailedJobRequestIDs mocks base method.
func (m *MockSchedulerRepository) GetFailedJobRequestIDs(ctx context.Context, partitionID string) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFailedJobRequestIDs", ctx, partitionID)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFailedJobRequestIDs indicates an expected call of GetFailedJobRequestIDs.
func (mr *MockSchedulerRepositoryMockRecorder) GetFailedJobRequestIDs(ctx, partitionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFailedJobRequestIDs", reflect.TypeOf((*MockSchedulerRepository)(nil).GetFailedJobRequestIDs), ctx, partitionID)
}

// GetTopUnscheduledRequests mocks base method.
func (m *MockSchedulerRepository) GetTopUnscheduledRequests(ctx context.Context, partitionID string) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTopUnscheduledRequests", ctx, partitionID)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTopUnscheduledRequests indicates an expected call of GetTopUnscheduledRequests.
func (mr *MockSchedulerRepositoryMockRecorder) GetTopUnscheduledRequests(ctx, partitionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTopUnscheduledRequests", reflect.TypeOf((*MockSchedulerRepository)(nil).GetTopUnscheduledRequests), ctx, partitionID)
}

// SupercedeOlderRequests mocks base method.
func (m *MockSchedulerRepository) SupercedeOlderRequests(ctx context.Context, resourceInstanceID string, version int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SupercedeOlderRequests", ctx, resourceInstanceID, version)
	ret0, _ := ret[0].(error)
	return ret0
}

// SupercedeOlderRequests indicates an expected call of SupercedeOlderRequests.
func (mr *MockSchedulerRepositoryMockRecorder) SupercedeOlderRequests(ctx, resourceInstanceID, version any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SupercedeOlderRequests", reflect.TypeOf((*MockSchedulerRepository)(nil).SupercedeOlderRequests), ctx, resourceInstanceID, version)
}

// UpsertJobAndSchedule mocks base method.
func (m *MockSchedulerRepository) UpsertJobAndSchedule(ctx context.Context, requestID, contextJSON, currentAtomicOperation string, timeoutSeconds, workflowVersion int) (string, int64, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertJobAndSchedule", ctx, requestID, contextJSON, currentAtomicOperation, timeoutSeconds, workflowVersion)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(bool)
	ret3, _ := ret[3].(error)
	return ret0, ret1, ret2, ret3
}

// UpsertJobAndSchedule indicates an expected call of UpsertJobAndSchedule.
func (mr *MockSchedulerRepositoryMockRecorder) UpsertJobAndSchedule(ctx, requestID, contextJSON, currentAtomicOperation, timeoutSeconds, workflowVersion any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertJobAndSchedule", reflect.TypeOf((*MockSchedulerRepository)(nil).UpsertJobAndSchedule), ctx, requestID, contextJSON, currentAtomicOperation, timeoutSeconds, workflowVersion)
}

// MockJobRepository is a mock of JobRepository interface.
type MockJobRepository struct {
	ctrl     *gomock.Controller
	recorder *MockJobRepositoryMockRecorder
	isgomock struct{}
}

// MockJobRepositoryMockRecorder is the mock recorder for MockJobRepository.
type MockJobRepositoryMockRecorder struct {
	mock *MockJobRepository
}

// NewMockJobRepository creates a new mock instance.
func NewMockJobRepository(ctrl *gomock.Controller) *MockJobRepository {
	mock := &MockJobRepository{ctrl: ctrl}
	mock.recorder = &MockJobRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockJobRepository) EXPECT() *MockJobRepositoryMockRecorder {
	return m.recorder
}

// AcquireJob mocks base method.
func (m *MockJobRepository) AcquireJob(ctx context.Context, resourceInstanceID, ownerID string, leaseDuration time.Duration) (*domain.Job, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AcquireJob", ctx, resourceInstanceID, ownerID, leaseDuration)
	ret0, _ := ret[0].(*domain.Job)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AcquireJob indicates an expected call of AcquireJob.
func (mr *MockJobRepositoryMockRecorder) AcquireJob(ctx, resourceInstanceID, ownerID, leaseDuration any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AcquireJob", reflect.TypeOf((*MockJobRepository)(nil).AcquireJob), ctx, resourceInstanceID, ownerID, leaseDuration)
}

// GetAvailableJob mocks base method.
func (m *MockJobRepository) GetAvailableJob(ctx context.Context) (*string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAvailableJob", ctx)
	ret0, _ := ret[0].(*string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAvailableJob indicates an expected call of GetAvailableJob.
func (mr *MockJobRepositoryMockRecorder) GetAvailableJob(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAvailableJob", reflect.TypeOf((*MockJobRepository)(nil).GetAvailableJob), ctx)
}

// ReleaseJob mocks base method.
func (m *MockJobRepository) ReleaseJob(ctx context.Context, resourceInstanceID, ownerID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReleaseJob", ctx, resourceInstanceID, ownerID)
	ret0, _ := ret[0].(error)
	return ret0
}

// ReleaseJob indicates an expected call of ReleaseJob.
func (mr *MockJobRepositoryMockRecorder) ReleaseJob(ctx, resourceInstanceID, ownerID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReleaseJob", reflect.TypeOf((*MockJobRepository)(nil).ReleaseJob), ctx, resourceInstanceID, ownerID)
}

// RenewJobLease mocks base method.
func (m *MockJobRepository) RenewJobLease(ctx context.Context, resourceInstanceID, ownerID string, leaseDuration time.Duration) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RenewJobLease", ctx, resourceInstanceID, ownerID, leaseDuration)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RenewJobLease indicates an expected call of RenewJobLease.
func (mr *MockJobRepositoryMockRecorder) RenewJobLease(ctx, resourceInstanceID, ownerID, leaseDuration any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RenewJobLease", reflect.TypeOf((*MockJobRepository)(nil).RenewJobLease), ctx, resourceInstanceID, ownerID, leaseDuration)
}

// UpdateJob mocks base method.
func (m *MockJobRepository) UpdateJob(ctx context.Context, resourceInstanceID, ownerID string, status domain.JobStatus, currentAtomicOperation string, operationTimeoutSeconds int, jobContext map[string]any) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateJob", ctx, resourceInstanceID, ownerID, status, currentAtomicOperation, operationTimeoutSeconds, jobContext)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateJob indicates an expected call of UpdateJob.
func (mr *MockJobRepositoryMockRecorder) UpdateJob(ctx, resourceInstanceID, ownerID, status, currentAtomicOperation, operationTimeoutSeconds, jobContext any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateJob", reflect.TypeOf((*MockJobRepository)(nil).UpdateJob), ctx, resourceInstanceID, ownerID, status, currentAtomicOperation, operationTimeoutSeconds, jobContext)
}

// UpdateJobStatus mocks base method.
func (m *MockJobRepository) UpdateJobStatus(ctx context.Context, resourceInstanceID, ownerID string, status domain.JobStatus) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateJobStatus", ctx, resourceInstanceID, ownerID, status)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateJobStatus indicates an expected call of UpdateJobStatus.
func (mr *MockJobRepositoryMockRecorder) UpdateJobStatus(ctx, resourceInstanceID, ownerID, status any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateJobStatus", reflect.TypeOf((*MockJobRepository)(nil).UpdateJobStatus), ctx, resourceInstanceID, ownerID, status)
}

// MockAgentStateRepository is a mock of AgentStateRepository interface.
type MockAgentStateRepository struct {
	ctrl     *gomock.Controller
	recorder *MockAgentStateRepositoryMockRecorder
	isgomock struct{}
}

// MockAgentStateRepositoryMockRecorder is the mock recorder for MockAgentStateRepository.
type MockAgentStateRepositoryMockRecorder struct {
	mock *MockAgentStateRepository
}

// NewMockAgentStateRepository creates a new mock instance.
func NewMockAgentStateRepository(ctrl *gomock.Controller) *MockAgentStateRepository {
	mock := &MockAgentStateRepository{ctrl: ctrl}
	mock.recorder = &MockAgentStateRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAgentStateRepository) EXPECT() *MockAgentStateRepositoryMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockAgentStateRepository) Delete(ctx context.Context, resourceInstanceID, agentName string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, resourceInstanceID, agentName)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockAgentStateRepositoryMockRecorder) Delete(ctx, resourceInstanceID, agentName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockAgentStateRepository)(nil).Delete), ctx, resourceInstanceID, agentName)
}

// GetAllForResource mocks base method.
func (m *MockAgentStateRepository) GetAllForResource(ctx context.Context, resourceInstanceID string) (map[string]*domain.AgentState, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllForResource", ctx, resourceInstanceID)
	ret0, _ := ret[0].(map[string]*domain.AgentState)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllForResource indicates an expected call of GetAllForResource.
func (mr *MockAgentStateRepositoryMockRecorder) GetAllForResource(ctx, resourceInstanceID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllForResource", reflect.TypeOf((*MockAgentStateRepository)(nil).GetAllForResource), ctx, resourceInstanceID)
}

// UpdateMetrics mocks base method.
func (m *MockAgentStateRepository) UpdateMetrics(ctx context.Context, resourceInstanceID, agentName string, metrics []*convergeplanev1.AgentInvocationMetrics) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateMetrics", ctx, resourceInstanceID, agentName, metrics)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateMetrics indicates an expected call of UpdateMetrics.
func (mr *MockAgentStateRepositoryMockRecorder) UpdateMetrics(ctx, resourceInstanceID, agentName, metrics any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateMetrics", reflect.TypeOf((*MockAgentStateRepository)(nil).UpdateMetrics), ctx, resourceInstanceID, agentName, metrics)
}

// UpsertLifecyclePolicy mocks base method.
func (m *MockAgentStateRepository) UpsertLifecyclePolicy(ctx context.Context, resourceInstanceID, agentName string, policy map[string]any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertLifecyclePolicy", ctx, resourceInstanceID, agentName, policy)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpsertLifecyclePolicy indicates an expected call of UpsertLifecyclePolicy.
func (mr *MockAgentStateRepositoryMockRecorder) UpsertLifecyclePolicy(ctx, resourceInstanceID, agentName, policy any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertLifecyclePolicy", reflect.TypeOf((*MockAgentStateRepository)(nil).UpsertLifecyclePolicy), ctx, resourceInstanceID, agentName, policy)
}

// UpsertRuntimePolicy mocks base method.
func (m *MockAgentStateRepository) UpsertRuntimePolicy(ctx context.Context, resourceInstanceID, agentName string, policy map[string]any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertRuntimePolicy", ctx, resourceInstanceID, agentName, policy)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpsertRuntimePolicy indicates an expected call of UpsertRuntimePolicy.
func (mr *MockAgentStateRepositoryMockRecorder) UpsertRuntimePolicy(ctx, resourceInstanceID, agentName, policy any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertRuntimePolicy", reflect.TypeOf((*MockAgentStateRepository)(nil).UpsertRuntimePolicy), ctx, resourceInstanceID, agentName, policy)
}

// MockCustomerRequestRepository is a mock of CustomerRequestRepository interface.
type MockCustomerRequestRepository struct {
	ctrl     *gomock.Controller
	recorder *MockCustomerRequestRepositoryMockRecorder
	isgomock struct{}
}

// MockCustomerRequestRepositoryMockRecorder is the mock recorder for MockCustomerRequestRepository.
type MockCustomerRequestRepositoryMockRecorder struct {
	mock *MockCustomerRequestRepository
}

// NewMockCustomerRequestRepository creates a new mock instance.
func NewMockCustomerRequestRepository(ctrl *gomock.Controller) *MockCustomerRequestRepository {
	mock := &MockCustomerRequestRepository{ctrl: ctrl}
	mock.recorder = &MockCustomerRequestRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCustomerRequestRepository) EXPECT() *MockCustomerRequestRepositoryMockRecorder {
	return m.recorder
}

// CompleteRequest mocks base method.
func (m *MockCustomerRequestRepository) CompleteRequest(ctx context.Context, id string) (*domain.CustomerRequest, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CompleteRequest", ctx, id)
	ret0, _ := ret[0].(*domain.CustomerRequest)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CompleteRequest indicates an expected call of CompleteRequest.
func (mr *MockCustomerRequestRepositoryMockRecorder) CompleteRequest(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CompleteRequest", reflect.TypeOf((*MockCustomerRequestRepository)(nil).CompleteRequest), ctx, id)
}

// Create mocks base method.
func (m *MockCustomerRequestRepository) Create(ctx context.Context, req *domain.CustomerRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, req)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockCustomerRequestRepositoryMockRecorder) Create(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockCustomerRequestRepository)(nil).Create), ctx, req)
}

// FailRequest mocks base method.
func (m *MockCustomerRequestRepository) FailRequest(ctx context.Context, id string) (*domain.CustomerRequest, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FailRequest", ctx, id)
	ret0, _ := ret[0].(*domain.CustomerRequest)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FailRequest indicates an expected call of FailRequest.
func (mr *MockCustomerRequestRepositoryMockRecorder) FailRequest(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FailRequest", reflect.TypeOf((*MockCustomerRequestRepository)(nil).FailRequest), ctx, id)
}

// Get mocks base method.
func (m *MockCustomerRequestRepository) Get(ctx context.Context, id string) (*domain.CustomerRequest, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, id)
	ret0, _ := ret[0].(*domain.CustomerRequest)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockCustomerRequestRepositoryMockRecorder) Get(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockCustomerRequestRepository)(nil).Get), ctx, id)
}

// UpdateStatus mocks base method.
func (m *MockCustomerRequestRepository) UpdateStatus(ctx context.Context, resourceInstanceID, id string, status domain.CustomerRequestStatus) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateStatus", ctx, resourceInstanceID, id, status)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateStatus indicates an expected call of UpdateStatus.
func (mr *MockCustomerRequestRepositoryMockRecorder) UpdateStatus(ctx, resourceInstanceID, id, status any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateStatus", reflect.TypeOf((*MockCustomerRequestRepository)(nil).UpdateStatus), ctx, resourceInstanceID, id, status)
}
