# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from convergeplane.v1 import lifecycle_pb2 as convergeplane_dot_v1_dot_lifecycle__pb2

GRPC_GENERATED_VERSION = '1.81.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in convergeplane/v1/lifecycle_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ResourceLifecycleServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateResource = channel.unary_unary(
                '/convergeplane.v1.ResourceLifecycleService/CreateResource',
                request_serializer=convergeplane_dot_v1_dot_lifecycle__pb2.CreateResourceRequest.SerializeToString,
                response_deserializer=convergeplane_dot_v1_dot_lifecycle__pb2.CreateResourceResponse.FromString,
                _registered_method=True)
        self.ReconcileResource = channel.unary_unary(
                '/convergeplane.v1.ResourceLifecycleService/ReconcileResource',
                request_serializer=convergeplane_dot_v1_dot_lifecycle__pb2.ReconcileResourceRequest.SerializeToString,
                response_deserializer=convergeplane_dot_v1_dot_lifecycle__pb2.ReconcileResourceResponse.FromString,
                _registered_method=True)
        self.DeleteResource = channel.unary_unary(
                '/convergeplane.v1.ResourceLifecycleService/DeleteResource',
                request_serializer=convergeplane_dot_v1_dot_lifecycle__pb2.DeleteResourceRequest.SerializeToString,
                response_deserializer=convergeplane_dot_v1_dot_lifecycle__pb2.DeleteResourceResponse.FromString,
                _registered_method=True)
        self.GetResourceState = channel.unary_unary(
                '/convergeplane.v1.ResourceLifecycleService/GetResourceState',
                request_serializer=convergeplane_dot_v1_dot_lifecycle__pb2.GetResourceStateRequest.SerializeToString,
                response_deserializer=convergeplane_dot_v1_dot_lifecycle__pb2.GetResourceStateResponse.FromString,
                _registered_method=True)
        self.SetAgentRuntimePolicy = channel.unary_unary(
                '/convergeplane.v1.ResourceLifecycleService/SetAgentRuntimePolicy',
                request_serializer=convergeplane_dot_v1_dot_lifecycle__pb2.SetAgentRuntimePolicyRequest.SerializeToString,
                response_deserializer=convergeplane_dot_v1_dot_lifecycle__pb2.SetAgentRuntimePolicyResponse.FromString,
                _registered_method=True)
        self.SetAgentLifecyclePolicy = channel.unary_unary(
                '/convergeplane.v1.ResourceLifecycleService/SetAgentLifecyclePolicy',
                request_serializer=convergeplane_dot_v1_dot_lifecycle__pb2.SetAgentLifecyclePolicyRequest.SerializeToString,
                response_deserializer=convergeplane_dot_v1_dot_lifecycle__pb2.SetAgentLifecyclePolicyResponse.FromString,
                _registered_method=True)
        self.DeleteAgent = channel.unary_unary(
                '/convergeplane.v1.ResourceLifecycleService/DeleteAgent',
                request_serializer=convergeplane_dot_v1_dot_lifecycle__pb2.DeleteAgentRequest.SerializeToString,
                response_deserializer=convergeplane_dot_v1_dot_lifecycle__pb2.DeleteAgentResponse.FromString,
                _registered_method=True)
        self.SetWorkflowLifecyclePolicy = channel.unary_unary(
                '/convergeplane.v1.ResourceLifecycleService/SetWorkflowLifecyclePolicy',
                request_serializer=convergeplane_dot_v1_dot_lifecycle__pb2.SetWorkflowLifecyclePolicyRequest.SerializeToString,
                response_deserializer=convergeplane_dot_v1_dot_lifecycle__pb2.SetWorkflowLifecyclePolicyResponse.FromString,
                _registered_method=True)
        self.ApproveWorkflow = channel.unary_unary(
                '/convergeplane.v1.ResourceLifecycleService/ApproveWorkflow',
                request_serializer=convergeplane_dot_v1_dot_lifecycle__pb2.ApproveWorkflowRequest.SerializeToString,
                response_deserializer=convergeplane_dot_v1_dot_lifecycle__pb2.ApproveWorkflowResponse.FromString,
                _registered_method=True)
        self.RejectWorkflow = channel.unary_unary(
                '/convergeplane.v1.ResourceLifecycleService/RejectWorkflow',
                request_serializer=convergeplane_dot_v1_dot_lifecycle__pb2.RejectWorkflowRequest.SerializeToString,
                response_deserializer=convergeplane_dot_v1_dot_lifecycle__pb2.RejectWorkflowResponse.FromString,
                _registered_method=True)
        self.ActivateWorkflow = channel.unary_unary(
                '/convergeplane.v1.ResourceLifecycleService/ActivateWorkflow',
                request_serializer=convergeplane_dot_v1_dot_lifecycle__pb2.ActivateWorkflowRequest.SerializeToString,
                response_deserializer=convergeplane_dot_v1_dot_lifecycle__pb2.ActivateWorkflowResponse.FromString,
                _registered_method=True)


class ResourceLifecycleServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def CreateResource(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReconcileResource(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteResource(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetResourceState(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetAgentRuntimePolicy(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetAgentLifecyclePolicy(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteAgent(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetWorkflowLifecyclePolicy(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ApproveWorkflow(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RejectWorkflow(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ActivateWorkflow(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ResourceLifecycleServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateResource': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateResource,
                    request_deserializer=convergeplane_dot_v1_dot_lifecycle__pb2.CreateResourceRequest.FromString,
                    response_serializer=convergeplane_dot_v1_dot_lifecycle__pb2.CreateResourceResponse.SerializeToString,
            ),
            'ReconcileResource': grpc.unary_unary_rpc_method_handler(
                    servicer.ReconcileResource,
                    request_deserializer=convergeplane_dot_v1_dot_lifecycle__pb2.ReconcileResourceRequest.FromString,
                    response_serializer=convergeplane_dot_v1_dot_lifecycle__pb2.ReconcileResourceResponse.SerializeToString,
            ),
            'DeleteResource': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteResource,
                    request_deserializer=convergeplane_dot_v1_dot_lifecycle__pb2.DeleteResourceRequest.FromString,
                    response_serializer=convergeplane_dot_v1_dot_lifecycle__pb2.DeleteResourceResponse.SerializeToString,
            ),
            'GetResourceState': grpc.unary_unary_rpc_method_handler(
                    servicer.GetResourceState,
                    request_deserializer=convergeplane_dot_v1_dot_lifecycle__pb2.GetResourceStateRequest.FromString,
                    response_serializer=convergeplane_dot_v1_dot_lifecycle__pb2.GetResourceStateResponse.SerializeToString,
            ),
            'SetAgentRuntimePolicy': grpc.unary_unary_rpc_method_handler(
                    servicer.SetAgentRuntimePolicy,
                    request_deserializer=convergeplane_dot_v1_dot_lifecycle__pb2.SetAgentRuntimePolicyRequest.FromString,
                    response_serializer=convergeplane_dot_v1_dot_lifecycle__pb2.SetAgentRuntimePolicyResponse.SerializeToString,
            ),
            'SetAgentLifecyclePolicy': grpc.unary_unary_rpc_method_handler(
                    servicer.SetAgentLifecyclePolicy,
                    request_deserializer=convergeplane_dot_v1_dot_lifecycle__pb2.SetAgentLifecyclePolicyRequest.FromString,
                    response_serializer=convergeplane_dot_v1_dot_lifecycle__pb2.SetAgentLifecyclePolicyResponse.SerializeToString,
            ),
            'DeleteAgent': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteAgent,
                    request_deserializer=convergeplane_dot_v1_dot_lifecycle__pb2.DeleteAgentRequest.FromString,
                    response_serializer=convergeplane_dot_v1_dot_lifecycle__pb2.DeleteAgentResponse.SerializeToString,
            ),
            'SetWorkflowLifecyclePolicy': grpc.unary_unary_rpc_method_handler(
                    servicer.SetWorkflowLifecyclePolicy,
                    request_deserializer=convergeplane_dot_v1_dot_lifecycle__pb2.SetWorkflowLifecyclePolicyRequest.FromString,
                    response_serializer=convergeplane_dot_v1_dot_lifecycle__pb2.SetWorkflowLifecyclePolicyResponse.SerializeToString,
            ),
            'ApproveWorkflow': grpc.unary_unary_rpc_method_handler(
                    servicer.ApproveWorkflow,
                    request_deserializer=convergeplane_dot_v1_dot_lifecycle__pb2.ApproveWorkflowRequest.FromString,
                    response_serializer=convergeplane_dot_v1_dot_lifecycle__pb2.ApproveWorkflowResponse.SerializeToString,
            ),
            'RejectWorkflow': grpc.unary_unary_rpc_method_handler(
                    servicer.RejectWorkflow,
                    request_deserializer=convergeplane_dot_v1_dot_lifecycle__pb2.RejectWorkflowRequest.FromString,
                    response_serializer=convergeplane_dot_v1_dot_lifecycle__pb2.RejectWorkflowResponse.SerializeToString,
            ),
            'ActivateWorkflow': grpc.unary_unary_rpc_method_handler(
                    servicer.ActivateWorkflow,
                    request_deserializer=convergeplane_dot_v1_dot_lifecycle__pb2.ActivateWorkflowRequest.FromString,
                    response_serializer=convergeplane_dot_v1_dot_lifecycle__pb2.ActivateWorkflowResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'convergeplane.v1.ResourceLifecycleService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('convergeplane.v1.ResourceLifecycleService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ResourceLifecycleService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateResource(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/convergeplane.v1.ResourceLifecycleService/CreateResource',
            convergeplane_dot_v1_dot_lifecycle__pb2.CreateResourceRequest.SerializeToString,
            convergeplane_dot_v1_dot_lifecycle__pb2.CreateResourceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReconcileResource(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/convergeplane.v1.ResourceLifecycleService/ReconcileResource',
            convergeplane_dot_v1_dot_lifecycle__pb2.ReconcileResourceRequest.SerializeToString,
            convergeplane_dot_v1_dot_lifecycle__pb2.ReconcileResourceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteResource(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/convergeplane.v1.ResourceLifecycleService/DeleteResource',
            convergeplane_dot_v1_dot_lifecycle__pb2.DeleteResourceRequest.SerializeToString,
            convergeplane_dot_v1_dot_lifecycle__pb2.DeleteResourceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetResourceState(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/convergeplane.v1.ResourceLifecycleService/GetResourceState',
            convergeplane_dot_v1_dot_lifecycle__pb2.GetResourceStateRequest.SerializeToString,
            convergeplane_dot_v1_dot_lifecycle__pb2.GetResourceStateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetAgentRuntimePolicy(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/convergeplane.v1.ResourceLifecycleService/SetAgentRuntimePolicy',
            convergeplane_dot_v1_dot_lifecycle__pb2.SetAgentRuntimePolicyRequest.SerializeToString,
            convergeplane_dot_v1_dot_lifecycle__pb2.SetAgentRuntimePolicyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetAgentLifecyclePolicy(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/convergeplane.v1.ResourceLifecycleService/SetAgentLifecyclePolicy',
            convergeplane_dot_v1_dot_lifecycle__pb2.SetAgentLifecyclePolicyRequest.SerializeToString,
            convergeplane_dot_v1_dot_lifecycle__pb2.SetAgentLifecyclePolicyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteAgent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/convergeplane.v1.ResourceLifecycleService/DeleteAgent',
            convergeplane_dot_v1_dot_lifecycle__pb2.DeleteAgentRequest.SerializeToString,
            convergeplane_dot_v1_dot_lifecycle__pb2.DeleteAgentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetWorkflowLifecyclePolicy(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/convergeplane.v1.ResourceLifecycleService/SetWorkflowLifecyclePolicy',
            convergeplane_dot_v1_dot_lifecycle__pb2.SetWorkflowLifecyclePolicyRequest.SerializeToString,
            convergeplane_dot_v1_dot_lifecycle__pb2.SetWorkflowLifecyclePolicyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ApproveWorkflow(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/convergeplane.v1.ResourceLifecycleService/ApproveWorkflow',
            convergeplane_dot_v1_dot_lifecycle__pb2.ApproveWorkflowRequest.SerializeToString,
            convergeplane_dot_v1_dot_lifecycle__pb2.ApproveWorkflowResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RejectWorkflow(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/convergeplane.v1.ResourceLifecycleService/RejectWorkflow',
            convergeplane_dot_v1_dot_lifecycle__pb2.RejectWorkflowRequest.SerializeToString,
            convergeplane_dot_v1_dot_lifecycle__pb2.RejectWorkflowResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ActivateWorkflow(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/convergeplane.v1.ResourceLifecycleService/ActivateWorkflow',
            convergeplane_dot_v1_dot_lifecycle__pb2.ActivateWorkflowRequest.SerializeToString,
            convergeplane_dot_v1_dot_lifecycle__pb2.ActivateWorkflowResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
