# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: convergeplane/v1/policy.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'convergeplane/v1/policy.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import duration_pb2 as google_dot_protobuf_dot_duration__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1d\x63onvergeplane/v1/policy.proto\x12\x10\x63onvergeplane.v1\x1a\x1egoogle/protobuf/duration.proto\"\x93\x02\n\tPolicySet\x12\x38\n\x0b\x63oncurrency\x18\x01 \x01(\x0b\x32#.convergeplane.v1.ConcurrencyPolicy\x12\x30\n\x07\x66\x61ilure\x18\x02 \x01(\x0b\x32\x1f.convergeplane.v1.FailurePolicy\x12\x45\n\x12maintenance_window\x18\x03 \x01(\x0b\x32).convergeplane.v1.MaintenanceWindowPolicy\x12\x30\n\x07upgrade\x18\x04 \x01(\x0b\x32\x1f.convergeplane.v1.UpgradePolicy\x12!\n\x19operation_timeout_seconds\x18\x05 \x01(\x05\"6\n\x11\x43oncurrencyPolicy\x12!\n\x19max_concurrent_operations\x18\x01 \x01(\x05\"V\n\rFailurePolicy\x12\x17\n\x0f\x65nable_rollback\x18\x01 \x01(\x08\x12,\n\x05retry\x18\x02 \x01(\x0b\x32\x1d.convergeplane.v1.RetryPolicy\"\xa2\x01\n\x0bRetryPolicy\x12\x13\n\x0bmax_retries\x18\x01 \x01(\x05\x12\x32\n\x0finitial_backoff\x18\x02 \x01(\x0b\x32\x19.google.protobuf.Duration\x12.\n\x0bmax_backoff\x18\x03 \x01(\x0b\x32\x19.google.protobuf.Duration\x12\x1a\n\x12\x62\x61\x63koff_multiplier\x18\x04 \x01(\x01\"O\n\x17MaintenanceWindowPolicy\x12\x34\n\x07windows\x18\x01 \x03(\x0b\x32#.convergeplane.v1.MaintenanceWindow\"Y\n\x11MaintenanceWindow\x12\x17\n\x0f\x63ron_expression\x18\x01 \x01(\t\x12+\n\x08\x64uration\x18\x02 \x01(\x0b\x32\x19.google.protobuf.Duration\"Q\n\rUpgradePolicy\x12\x12\n\nauto_pause\x18\x01 \x01(\x08\x12,\n\tbake_time\x18\x02 \x01(\x0b\x32\x19.google.protobuf.DurationBMZKgithub.com/convergeplane/convergeplane/gen/convergeplane/v1;convergeplanev1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'convergeplane.v1.policy_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'ZKgithub.com/convergeplane/convergeplane/gen/convergeplane/v1;convergeplanev1'
  _globals['_POLICYSET']._serialized_start=84
  _globals['_POLICYSET']._serialized_end=359
  _globals['_CONCURRENCYPOLICY']._serialized_start=361
  _globals['_CONCURRENCYPOLICY']._serialized_end=415
  _globals['_FAILUREPOLICY']._serialized_start=417
  _globals['_FAILUREPOLICY']._serialized_end=503
  _globals['_RETRYPOLICY']._serialized_start=506
  _globals['_RETRYPOLICY']._serialized_end=668
  _globals['_MAINTENANCEWINDOWPOLICY']._serialized_start=670
  _globals['_MAINTENANCEWINDOWPOLICY']._serialized_end=749
  _globals['_MAINTENANCEWINDOW']._serialized_start=751
  _globals['_MAINTENANCEWINDOW']._serialized_end=840
  _globals['_UPGRADEPOLICY']._serialized_start=842
  _globals['_UPGRADEPOLICY']._serialized_end=923
# @@protoc_insertion_point(module_scope)
