# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: convergeplane/v1/pricing.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'convergeplane/v1/pricing.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1e\x63onvergeplane/v1/pricing.proto\x12\x10\x63onvergeplane.v1\"M\n\x0cModelPricing\x12\x10\n\x08model_id\x18\x01 \x01(\t\x12\x14\n\x0cinput_per_1m\x18\x02 \x01(\x01\x12\x15\n\routput_per_1m\x18\x03 \x01(\x01\x42MZKgithub.com/convergeplane/convergeplane/gen/convergeplane/v1;convergeplanev1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'convergeplane.v1.pricing_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'ZKgithub.com/convergeplane/convergeplane/gen/convergeplane/v1;convergeplanev1'
  _globals['_MODELPRICING']._serialized_start=52
  _globals['_MODELPRICING']._serialized_end=129
# @@protoc_insertion_point(module_scope)
