# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: convergeplane/v1/registration.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'convergeplane/v1/registration.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from convergeplane.v1 import tenant_group_pb2 as convergeplane_dot_v1_dot_tenant__group__pb2
from convergeplane.v1 import tenant_pb2 as convergeplane_dot_v1_dot_tenant__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n#convergeplane/v1/registration.proto\x12\x10\x63onvergeplane.v1\x1a#convergeplane/v1/tenant_group.proto\x1a\x1d\x63onvergeplane/v1/tenant.proto\"O\n\x18\x43reateTenantGroupRequest\x12\x33\n\x0ctenant_group\x18\x01 \x01(\x0b\x32\x1d.convergeplane.v1.TenantGroup\"P\n\x19\x43reateTenantGroupResponse\x12\x33\n\x0ctenant_group\x18\x01 \x01(\x0b\x32\x1d.convergeplane.v1.TenantGroup\"#\n\x15GetTenantGroupRequest\x12\n\n\x02id\x18\x01 \x01(\t\"M\n\x16GetTenantGroupResponse\x12\x33\n\x0ctenant_group\x18\x01 \x01(\x0b\x32\x1d.convergeplane.v1.TenantGroup\"?\n\x13\x43reateTenantRequest\x12(\n\x06tenant\x18\x01 \x01(\x0b\x32\x18.convergeplane.v1.Tenant\"@\n\x14\x43reateTenantResponse\x12(\n\x06tenant\x18\x01 \x01(\x0b\x32\x18.convergeplane.v1.Tenant\"\x1e\n\x10GetTenantRequest\x12\n\n\x02id\x18\x01 \x01(\t\"=\n\x11GetTenantResponse\x12(\n\x06tenant\x18\x01 \x01(\x0b\x32\x18.convergeplane.v1.Tenant\"&\n\x18\x44\x65leteTenantGroupRequest\x12\n\n\x02id\x18\x01 \x01(\t\"\x1b\n\x19\x44\x65leteTenantGroupResponse\"!\n\x13\x44\x65leteTenantRequest\x12\n\n\x02id\x18\x01 \x01(\t\"\x16\n\x14\x44\x65leteTenantResponse2\xea\x04\n\x13RegistrationService\x12l\n\x11\x43reateTenantGroup\x12*.convergeplane.v1.CreateTenantGroupRequest\x1a+.convergeplane.v1.CreateTenantGroupResponse\x12\x63\n\x0eGetTenantGroup\x12\'.convergeplane.v1.GetTenantGroupRequest\x1a(.convergeplane.v1.GetTenantGroupResponse\x12l\n\x11\x44\x65leteTenantGroup\x12*.convergeplane.v1.DeleteTenantGroupRequest\x1a+.convergeplane.v1.DeleteTenantGroupResponse\x12]\n\x0c\x43reateTenant\x12%.convergeplane.v1.CreateTenantRequest\x1a&.convergeplane.v1.CreateTenantResponse\x12T\n\tGetTenant\x12\".convergeplane.v1.GetTenantRequest\x1a#.convergeplane.v1.GetTenantResponse\x12]\n\x0c\x44\x65leteTenant\x12%.convergeplane.v1.DeleteTenantRequest\x1a&.convergeplane.v1.DeleteTenantResponseBMZKgithub.com/convergeplane/convergeplane/gen/convergeplane/v1;convergeplanev1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'convergeplane.v1.registration_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'ZKgithub.com/convergeplane/convergeplane/gen/convergeplane/v1;convergeplanev1'
  _globals['_CREATETENANTGROUPREQUEST']._serialized_start=125
  _globals['_CREATETENANTGROUPREQUEST']._serialized_end=204
  _globals['_CREATETENANTGROUPRESPONSE']._serialized_start=206
  _globals['_CREATETENANTGROUPRESPONSE']._serialized_end=286
  _globals['_GETTENANTGROUPREQUEST']._serialized_start=288
  _globals['_GETTENANTGROUPREQUEST']._serialized_end=323
  _globals['_GETTENANTGROUPRESPONSE']._serialized_start=325
  _globals['_GETTENANTGROUPRESPONSE']._serialized_end=402
  _globals['_CREATETENANTREQUEST']._serialized_start=404
  _globals['_CREATETENANTREQUEST']._serialized_end=467
  _globals['_CREATETENANTRESPONSE']._serialized_start=469
  _globals['_CREATETENANTRESPONSE']._serialized_end=533
  _globals['_GETTENANTREQUEST']._serialized_start=535
  _globals['_GETTENANTREQUEST']._serialized_end=565
  _globals['_GETTENANTRESPONSE']._serialized_start=567
  _globals['_GETTENANTRESPONSE']._serialized_end=628
  _globals['_DELETETENANTGROUPREQUEST']._serialized_start=630
  _globals['_DELETETENANTGROUPREQUEST']._serialized_end=668
  _globals['_DELETETENANTGROUPRESPONSE']._serialized_start=670
  _globals['_DELETETENANTGROUPRESPONSE']._serialized_end=697
  _globals['_DELETETENANTREQUEST']._serialized_start=699
  _globals['_DELETETENANTREQUEST']._serialized_end=732
  _globals['_DELETETENANTRESPONSE']._serialized_start=734
  _globals['_DELETETENANTRESPONSE']._serialized_end=756
  _globals['_REGISTRATIONSERVICE']._serialized_start=759
  _globals['_REGISTRATIONSERVICE']._serialized_end=1377
# @@protoc_insertion_point(module_scope)
