# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from convergeplane.v1 import registration_pb2 as convergeplane_dot_v1_dot_registration__pb2

GRPC_GENERATED_VERSION = '1.81.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in convergeplane/v1/registration_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class RegistrationServiceStub:
    """RegistrationService handles setup and configuration of tenant groups,
    tenants, and policies.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateTenantGroup = channel.unary_unary(
                '/convergeplane.v1.RegistrationService/CreateTenantGroup',
                request_serializer=convergeplane_dot_v1_dot_registration__pb2.CreateTenantGroupRequest.SerializeToString,
                response_deserializer=convergeplane_dot_v1_dot_registration__pb2.CreateTenantGroupResponse.FromString,
                _registered_method=True)
        self.GetTenantGroup = channel.unary_unary(
                '/convergeplane.v1.RegistrationService/GetTenantGroup',
                request_serializer=convergeplane_dot_v1_dot_registration__pb2.GetTenantGroupRequest.SerializeToString,
                response_deserializer=convergeplane_dot_v1_dot_registration__pb2.GetTenantGroupResponse.FromString,
                _registered_method=True)
        self.DeleteTenantGroup = channel.unary_unary(
                '/convergeplane.v1.RegistrationService/DeleteTenantGroup',
                request_serializer=convergeplane_dot_v1_dot_registration__pb2.DeleteTenantGroupRequest.SerializeToString,
                response_deserializer=convergeplane_dot_v1_dot_registration__pb2.DeleteTenantGroupResponse.FromString,
                _registered_method=True)
        self.CreateTenant = channel.unary_unary(
                '/convergeplane.v1.RegistrationService/CreateTenant',
                request_serializer=convergeplane_dot_v1_dot_registration__pb2.CreateTenantRequest.SerializeToString,
                response_deserializer=convergeplane_dot_v1_dot_registration__pb2.CreateTenantResponse.FromString,
                _registered_method=True)
        self.GetTenant = channel.unary_unary(
                '/convergeplane.v1.RegistrationService/GetTenant',
                request_serializer=convergeplane_dot_v1_dot_registration__pb2.GetTenantRequest.SerializeToString,
                response_deserializer=convergeplane_dot_v1_dot_registration__pb2.GetTenantResponse.FromString,
                _registered_method=True)
        self.DeleteTenant = channel.unary_unary(
                '/convergeplane.v1.RegistrationService/DeleteTenant',
                request_serializer=convergeplane_dot_v1_dot_registration__pb2.DeleteTenantRequest.SerializeToString,
                response_deserializer=convergeplane_dot_v1_dot_registration__pb2.DeleteTenantResponse.FromString,
                _registered_method=True)
        self.SetModelPricing = channel.unary_unary(
                '/convergeplane.v1.RegistrationService/SetModelPricing',
                request_serializer=convergeplane_dot_v1_dot_registration__pb2.SetModelPricingRequest.SerializeToString,
                response_deserializer=convergeplane_dot_v1_dot_registration__pb2.SetModelPricingResponse.FromString,
                _registered_method=True)
        self.ListModelPricing = channel.unary_unary(
                '/convergeplane.v1.RegistrationService/ListModelPricing',
                request_serializer=convergeplane_dot_v1_dot_registration__pb2.ListModelPricingRequest.SerializeToString,
                response_deserializer=convergeplane_dot_v1_dot_registration__pb2.ListModelPricingResponse.FromString,
                _registered_method=True)


class RegistrationServiceServicer:
    """RegistrationService handles setup and configuration of tenant groups,
    tenants, and policies.
    """

    def CreateTenantGroup(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTenantGroup(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteTenantGroup(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateTenant(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTenant(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteTenant(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetModelPricing(self, request, context):
        """Pricing is scoped to the caller's tenant group (resolved from the API key).
        SetModelPricing overrides a model's rate; ListModelPricing returns the
        effective rates (built-in defaults merged with the caller's overrides).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListModelPricing(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RegistrationServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateTenantGroup': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateTenantGroup,
                    request_deserializer=convergeplane_dot_v1_dot_registration__pb2.CreateTenantGroupRequest.FromString,
                    response_serializer=convergeplane_dot_v1_dot_registration__pb2.CreateTenantGroupResponse.SerializeToString,
            ),
            'GetTenantGroup': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTenantGroup,
                    request_deserializer=convergeplane_dot_v1_dot_registration__pb2.GetTenantGroupRequest.FromString,
                    response_serializer=convergeplane_dot_v1_dot_registration__pb2.GetTenantGroupResponse.SerializeToString,
            ),
            'DeleteTenantGroup': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteTenantGroup,
                    request_deserializer=convergeplane_dot_v1_dot_registration__pb2.DeleteTenantGroupRequest.FromString,
                    response_serializer=convergeplane_dot_v1_dot_registration__pb2.DeleteTenantGroupResponse.SerializeToString,
            ),
            'CreateTenant': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateTenant,
                    request_deserializer=convergeplane_dot_v1_dot_registration__pb2.CreateTenantRequest.FromString,
                    response_serializer=convergeplane_dot_v1_dot_registration__pb2.CreateTenantResponse.SerializeToString,
            ),
            'GetTenant': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTenant,
                    request_deserializer=convergeplane_dot_v1_dot_registration__pb2.GetTenantRequest.FromString,
                    response_serializer=convergeplane_dot_v1_dot_registration__pb2.GetTenantResponse.SerializeToString,
            ),
            'DeleteTenant': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteTenant,
                    request_deserializer=convergeplane_dot_v1_dot_registration__pb2.DeleteTenantRequest.FromString,
                    response_serializer=convergeplane_dot_v1_dot_registration__pb2.DeleteTenantResponse.SerializeToString,
            ),
            'SetModelPricing': grpc.unary_unary_rpc_method_handler(
                    servicer.SetModelPricing,
                    request_deserializer=convergeplane_dot_v1_dot_registration__pb2.SetModelPricingRequest.FromString,
                    response_serializer=convergeplane_dot_v1_dot_registration__pb2.SetModelPricingResponse.SerializeToString,
            ),
            'ListModelPricing': grpc.unary_unary_rpc_method_handler(
                    servicer.ListModelPricing,
                    request_deserializer=convergeplane_dot_v1_dot_registration__pb2.ListModelPricingRequest.FromString,
                    response_serializer=convergeplane_dot_v1_dot_registration__pb2.ListModelPricingResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'convergeplane.v1.RegistrationService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('convergeplane.v1.RegistrationService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class RegistrationService:
    """RegistrationService handles setup and configuration of tenant groups,
    tenants, and policies.
    """

    @staticmethod
    def CreateTenantGroup(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/convergeplane.v1.RegistrationService/CreateTenantGroup',
            convergeplane_dot_v1_dot_registration__pb2.CreateTenantGroupRequest.SerializeToString,
            convergeplane_dot_v1_dot_registration__pb2.CreateTenantGroupResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetTenantGroup(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/convergeplane.v1.RegistrationService/GetTenantGroup',
            convergeplane_dot_v1_dot_registration__pb2.GetTenantGroupRequest.SerializeToString,
            convergeplane_dot_v1_dot_registration__pb2.GetTenantGroupResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteTenantGroup(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/convergeplane.v1.RegistrationService/DeleteTenantGroup',
            convergeplane_dot_v1_dot_registration__pb2.DeleteTenantGroupRequest.SerializeToString,
            convergeplane_dot_v1_dot_registration__pb2.DeleteTenantGroupResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateTenant(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/convergeplane.v1.RegistrationService/CreateTenant',
            convergeplane_dot_v1_dot_registration__pb2.CreateTenantRequest.SerializeToString,
            convergeplane_dot_v1_dot_registration__pb2.CreateTenantResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetTenant(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/convergeplane.v1.RegistrationService/GetTenant',
            convergeplane_dot_v1_dot_registration__pb2.GetTenantRequest.SerializeToString,
            convergeplane_dot_v1_dot_registration__pb2.GetTenantResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteTenant(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/convergeplane.v1.RegistrationService/DeleteTenant',
            convergeplane_dot_v1_dot_registration__pb2.DeleteTenantRequest.SerializeToString,
            convergeplane_dot_v1_dot_registration__pb2.DeleteTenantResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetModelPricing(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/convergeplane.v1.RegistrationService/SetModelPricing',
            convergeplane_dot_v1_dot_registration__pb2.SetModelPricingRequest.SerializeToString,
            convergeplane_dot_v1_dot_registration__pb2.SetModelPricingResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListModelPricing(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/convergeplane.v1.RegistrationService/ListModelPricing',
            convergeplane_dot_v1_dot_registration__pb2.ListModelPricingRequest.SerializeToString,
            convergeplane_dot_v1_dot_registration__pb2.ListModelPricingResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
