# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: convergeplane/v1/tenant_group.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'convergeplane/v1/tenant_group.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2
from convergeplane.v1 import tenant_pb2 as convergeplane_dot_v1_dot_tenant__pb2
from convergeplane.v1 import policy_pb2 as convergeplane_dot_v1_dot_policy__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n#convergeplane/v1/tenant_group.proto\x12\x10\x63onvergeplane.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1d\x63onvergeplane/v1/tenant.proto\x1a\x1d\x63onvergeplane/v1/policy.proto\"\xb1\x01\n\x0bTenantGroup\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12)\n\x07tenants\x18\x03 \x03(\x0b\x32\x18.convergeplane.v1.Tenant\x12-\n\x08policies\x18\x04 \x01(\x0b\x32\x1b.convergeplane.v1.PolicySet\x12.\n\ncreated_at\x18\x05 \x01(\x0b\x32\x1a.google.protobuf.TimestampBMZKgithub.com/convergeplane/convergeplane/gen/convergeplane/v1;convergeplanev1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'convergeplane.v1.tenant_group_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'ZKgithub.com/convergeplane/convergeplane/gen/convergeplane/v1;convergeplanev1'
  _globals['_TENANTGROUP']._serialized_start=153
  _globals['_TENANTGROUP']._serialized_end=330
# @@protoc_insertion_point(module_scope)
