# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: convergeplane/v1/worker.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'convergeplane/v1/worker.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from convergeplane.v1 import operation_pb2 as convergeplane_dot_v1_dot_operation__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1d\x63onvergeplane/v1/worker.proto\x12\x10\x63onvergeplane.v1\x1a convergeplane/v1/operation.proto\"\x94\x01\n\rWorkerMessage\x12\x12\n\nsession_id\x18\x01 \x01(\t\x12/\n\x05ready\x18\x02 \x01(\x0b\x32\x1e.convergeplane.v1.ReadyForWorkH\x00\x12\x33\n\x06update\x18\x03 \x01(\x0b\x32!.convergeplane.v1.OperationUpdateH\x00\x42\t\n\x07payload\"C\n\x10WorkerCapability\x12\x15\n\rresource_type\x18\x01 \x01(\t\x12\x18\n\x10workflow_version\x18\x02 \x01(\x05\"H\n\x0cReadyForWork\x12\x38\n\x0c\x63\x61pabilities\x18\x01 \x03(\x0b\x32\".convergeplane.v1.WorkerCapability\"`\n\x0fOperationUpdate\x12\x14\n\x0coperation_id\x18\x01 \x01(\t\x12\x37\n\x06result\x18\x02 \x01(\x0b\x32\'.convergeplane.v1.AtomicOperationResult\"\x84\x01\n\rServerCommand\x12\x33\n\x06launch\x18\x01 \x01(\x0b\x32!.convergeplane.v1.LaunchOperationH\x00\x12\x33\n\x06\x63\x61ncel\x18\x02 \x01(\x0b\x32!.convergeplane.v1.CancelOperationH\x00\x42\t\n\x07payload\"G\n\x0fLaunchOperation\x12\x34\n\toperation\x18\x01 \x01(\x0b\x32!.convergeplane.v1.AtomicOperation\"\'\n\x0f\x43\x61ncelOperation\x12\x14\n\x0coperation_id\x18\x01 \x01(\t2f\n\rWorkerService\x12U\n\rWorkerSession\x12\x1f.convergeplane.v1.WorkerMessage\x1a\x1f.convergeplane.v1.ServerCommand(\x01\x30\x01\x42MZKgithub.com/convergeplane/convergeplane/gen/convergeplane/v1;convergeplanev1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'convergeplane.v1.worker_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'ZKgithub.com/convergeplane/convergeplane/gen/convergeplane/v1;convergeplanev1'
  _globals['_WORKERMESSAGE']._serialized_start=86
  _globals['_WORKERMESSAGE']._serialized_end=234
  _globals['_WORKERCAPABILITY']._serialized_start=236
  _globals['_WORKERCAPABILITY']._serialized_end=303
  _globals['_READYFORWORK']._serialized_start=305
  _globals['_READYFORWORK']._serialized_end=377
  _globals['_OPERATIONUPDATE']._serialized_start=379
  _globals['_OPERATIONUPDATE']._serialized_end=475
  _globals['_SERVERCOMMAND']._serialized_start=478
  _globals['_SERVERCOMMAND']._serialized_end=610
  _globals['_LAUNCHOPERATION']._serialized_start=612
  _globals['_LAUNCHOPERATION']._serialized_end=683
  _globals['_CANCELOPERATION']._serialized_start=685
  _globals['_CANCELOPERATION']._serialized_end=724
  _globals['_WORKERSERVICE']._serialized_start=726
  _globals['_WORKERSERVICE']._serialized_end=828
# @@protoc_insertion_point(module_scope)
